service: kinesis-streams

custom:
  names:
    kinesis: ${self:service}-stream

provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  stage: dev
  memorySize: 128
  iamRoleStatements:
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "kinesis:*"
        - "logs:*"

functions:
  dataReceiver:
    handler: handler.dataReceiver
  logger:
    handler: handler.logger
    events:
      - stream:
          type: kinesis
          arn:
            Fn::GetAtt:
              - KinesisStream
              - Arn
resources:
  Resources:
    KinesisStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: ${self:custom.names.kinesis}
        ShardCount: 1