service: simulate-lambda

plugins:
  - serverless-plugin-simulate

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello

custom:
  simulate:
    services: docker-compose.yml
