service: simulate-lambda

plugins:
  - serverless-plugin-simulate

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

custom:
  simulate:
    services: docker-compose.yml
