service: serverless-wechat

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 120
  region: ap-northeast-2

functions:
  lambda:
    handler: lambda.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      TOKEN: ${file(./config.yml):TOKEN}
      APP_ID: ${file(./config.yml):TOKEN}
      AESKey: ${file(./config.yml):TOKEN}
